//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Skylight.Editor.SceneLookupGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class SceneLookup {

public const int GameRoot = 0;
public const int PaperPleasePrototype = 1;
public const int Prototype_AVG_System = 2;
public const int SceneKnifeAndTransformDoor = 3;
public const int UITestScene = 4;


    private const int TotalComponents = 5;

    private static readonly string[] sceneLists = {
"GameRoot",
"PaperPleasePrototype",
"Prototype_AVG_System",
"SceneKnifeAndTransformDoor",
"UITestScene"
    };

    public static string Get(SceneLookupEnum eScene)
    {
     return sceneLists [(int)eScene];
    }
}

public enum SceneLookupEnum
{
GameRoot = 0,
PaperPleasePrototype = 1,
Prototype_AVG_System = 2,
SceneKnifeAndTransformDoor = 3,
UITestScene = 4
}
