//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Skylight.Editor.SceneLookupGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class SceneLookup {

public const int SceneKnifeAndTransformDoor = 0;
public const int SceneRoot = 1;


    private const int TotalComponents = 2;

    private static readonly string[] sceneLists = {
"SceneKnifeAndTransformDoor",
"SceneRoot"
    };

    public static string Get(SceneLookupEnum eScene)
    {
     return sceneLists [(int)eScene];
    }
}

public enum SceneLookupEnum
{
SceneKnifeAndTransformDoor = 0,
SceneRoot = 1
}
