//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Skylight.Editor.SceneLookupGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class SceneLookup {

public const int GameRoot = 0;
public const int PaperPleasePrototype = 1;
public const int SceneKnifeAndTransformDoor = 2;


    private const int TotalComponents = 3;

    private static readonly string[] sceneLists = {
"GameRoot",
"PaperPleasePrototype",
"SceneKnifeAndTransformDoor"
    };

    public static string Get(SceneLookupEnum eScene)
    {
     return sceneLists [(int)eScene];
    }
}

public enum SceneLookupEnum
{
GameRoot = 0,
PaperPleasePrototype = 1,
SceneKnifeAndTransformDoor = 2
}
